 => [web 1/5] FROM docker.io/library/python:3.11-slim@sha256:1d6131b5d479888b43200645e03a784  13.7s
 => => resolve docker.io/library/python:3.11-slim@sha256:1d6131b5d479888b43200645e03a78443c71  0.2s
 => => sha256:1d6131b5d479888b43200645e03a78443c7157efbdb730e6b48129740727c 10.37kB / 10.37kB  0.0s
 => => sha256:8df0e8faf75b3c17ac33dc90d76787bbbcae142679e11da8c6f16afae5605ea 1.75kB / 1.75kB  0.0s
 => => sha256:2ba2e944f9cd164e42cf5e50da9ddeff526b43886a47738a75ab424624cdc42 5.38kB / 5.38kB  0.0s
 => => sha256:396b1da7636e2dcd10565cb4f2f952cbb4a8a38b58d3b86a2cacb172fb701 29.77MB / 29.77MB  2.2s
 => => sha256:fcec5a125fd8f69ba9d5c3fd9ecf3810f95775d4d5694ed731adcdeae1cff90 1.29MB / 1.29MB  0.7s
 => => sha256:a27cb4be70170df84ec3045fb7d33b3eb7018cb39fc029037429d9f063627 14.64MB / 14.64MB  3.1s
 => => sha256:1961ca026b04e3e3720545ee5a8e05e60692056663c685c5d2437bf3ad9e6e08 249B / 249B     3.2s
 => => extracting sha256:396b1da7636e2dcd10565cb4f2f952cbb4a8a38b58d3b86a2cacb172fb70117c      2.1s
 => => extracting sha256:fcec5a125fd8f69ba9d5c3fd9ecf3810f95775d4d5694ed731adcdeae1cff909      2.8s
 => => extracting sha256:a27cb4be70170df84ec3045fb7d33b3eb7018cb39fc029037429d9f06362737f      1.2s
 => => extracting sha256:1961ca026b04e3e3720545ee5a8e05e60692056663c685c5d2437bf3ad9e6e08      0.0s
 => [web internal] load build context                                                          8.6s
 => => transferring context: 121.66MB                                                          6.0s
 => [web 2/5] WORKDIR /app                                                                    12.6s
 => [web 3/5] COPY requirements.txt .                                                          0.2s
 => [web 4/5] RUN pip install --no-cache-dir -r requirements.txt                              27.5s
 => [web 5/5] COPY . .                                                                         4.3s
 => [web] exporting to image                                                                   2.7s
 => => exporting layers                                                                        2.5s
 => => writing image sha256:ea4efe97e746aca3e53739f90da35fe9b3658c10abf21111e31c301cbce5966c   0.0s
 => => naming to docker.io/library/dashboard-web                                               0.0s
WARN[0000] /var/dashboard/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 15/15
 ✔ db Pulled                                                                                  24.1s
   ✔ 396b1da7636e Already exists                                                               0.0s
   ✔ fca2566eba32 Pull complete                                                                0.1s
   ✔ 631fe8c6d606 Pull complete                                                                0.3s
   ✔ 77c7671c4414 Pull complete                                                                0.1s
   ✔ 2d9e29180a27 Pull complete                                                                0.5s
   ✔ c6bcc2c9a041 Pull complete                                                                0.4s
   ✔ ac4b721eb66f Pull complete                                                                0.4s
   ✔ 606bd164980e Pull complete                                                                0.8s
   ✔ f5dfd246bc6e Pull complete                                                                2.7s
   ✔ ba7036bb0a60 Pull complete                                                                0.8s
   ✔ 799f859abbbd Pull complete                                                                1.0s
   ✔ d903e777080c Pull complete                                                                1.0s
   ✔ 04adcb462801 Pull complete                                                                1.3s
   ✔ 5c10925b29ff Pull complete                                                                1.4s
[+] Running 1/3
 ✔ Network dashboard_default  Created                                                          0.2s
 ⠇ Container dashboard-db-1   Created                                                          1.8s
 ⠙ Container dashboard-web-1  Created                                                          0.2s
Attaching to db-1, web-1
db-1   | The files belonging to this database system will be owned by user "postgres".
db-1   | This user must also own the server process.
db-1   |
db-1   | The database cluster will be initialized with locale "en_US.utf8".
db-1   | The default database encoding has accordingly been set to "UTF8".
db-1   | The default text search configuration will be set to "english".
db-1   |
db-1   | Data page checksums are disabled.
db-1   |
db-1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1   | creating subdirectories ... ok
db-1   | selecting dynamic shared memory implementation ... posix
db-1   | selecting default max_connections ... 100
db-1   | selecting default shared_buffers ... 128MB
db-1   | selecting default time zone ... Etc/UTC
db-1   | creating configuration files ... ok
db-1   | running bootstrap script ... ok
db-1   | performing post-bootstrap initialization ... ok
db-1   | syncing data to disk ... ok
db-1   |
db-1   |
db-1   | Success. You can now start the database server using:
db-1   |
db-1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1   |
db-1   | initdb: warning: enabling "trust" authentication for local connections
db-1   | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1   | waiting for server to start....2025-08-19 06:38:09.203 UTC [47] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
db-1   | 2025-08-19 06:38:09.231 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1   | 2025-08-19 06:38:09.298 UTC [50] LOG:  database system was shut down at 2025-08-19 06:38:07 UTC
db-1   | 2025-08-19 06:38:09.336 UTC [47] LOG:  database system is ready to accept connections
db-1   |  done
db-1   | server started
db-1   | CREATE DATABASE
db-1   |
db-1   |
db-1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1   |
db-1   | 2025-08-19 06:38:10.131 UTC [47] LOG:  received fast shutdown request
db-1   | waiting for server to shut down....2025-08-19 06:38:10.159 UTC [47] LOG:  aborting any active transactions
db-1   | 2025-08-19 06:38:10.169 UTC [47] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
db-1   | 2025-08-19 06:38:10.170 UTC [48] LOG:  shutting down
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/bin/uvicorn", line 8, in <module>
web-1  |     sys.exit(main())
web-1  |              ^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
web-1  |     return self.main(*args, **kwargs)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1363, in main
web-1  |     rv = self.invoke(ctx)
web-1  |          ^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
web-1  |     return ctx.invoke(self.callback, **ctx.params)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 794, in invoke
web-1  |     return callback(*args, **kwargs)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 413, in main
web-1  |     run(
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 580, in run
web-1  |     server.run()
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 67, in run
web-1  |     return asyncio.run(self.serve(sockets=sockets))
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
web-1  |     return runner.run(main)
web-1  |            ^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
web-1  |     return self._loop.run_until_complete(task)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 71, in serve
web-1  |     await self._serve(sockets)
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 78, in _serve
web-1  |     config.load()
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 436, in load
web-1  |     self.loaded_app = import_from_string(self.app)
web-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
web-1  |     module = importlib.import_module(module_str)
web-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
db-1   | 2025-08-19 06:38:10.194 UTC [48] LOG:  checkpoint starting: shutdown immediate
web-1  |     return _bootstrap._gcd_import(name[level:], package, level)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
web-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
web-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
web-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
web-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
web-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
web-1  |   File "/app/app/main.py", line 2, in <module>
web-1  |     from app.api.routes import auth, user
web-1  |   File "/app/app/api/routes/auth.py", line 4, in <module>
web-1  |     from app.db.session import get_db
web-1  |   File "/app/app/db/session.py", line 3, in <module>
web-1  |     from app.core.config import settings
web-1  |   File "/app/app/core/config.py", line 1, in <module>
web-1  |     from pydantic import BaseSettings
web-1  |   File "/usr/local/lib/python3.11/site-packages/pydantic/__init__.py", line 426, in __getattr__
web-1  |     return _getattr_migration(attr_name)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 296, in wrapper
web-1  |     raise PydanticImportError(
web-1  | pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.11/migration/#basesettings-has-moved-to-pydantic-settings for more details.
web-1  |
web-1  | For further information visit https://errors.pydantic.dev/2.11/u/import-error
db-1   | 2025-08-19 06:38:10.780 UTC [48] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.075 s, sync=0.433 s, total=0.611 s; sync files=301, longest=0.362 s, average=0.002 s; distance=4239 kB, estimate=4239 kB
db-1   | 2025-08-19 06:38:10.788 UTC [47] LOG:  database system is shut down
db-1   |  done
db-1   | server stopped
db-1   |
db-1   | PostgreSQL init process complete; ready for start up.
db-1   |
db-1   | 2025-08-19 06:38:10.937 UTC [1] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
db-1   | 2025-08-19 06:38:10.940 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1   | 2025-08-19 06:38:10.941 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1   | 2025-08-19 06:38:11.005 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
web-1 exited with code 1
db-1   | 2025-08-19 06:38:11.057 UTC [63] LOG:  database system was shut down at 2025-08-19 06:38:10 UTC
db-1   | 2025-08-19 06:38:11.076 UTC [1] LOG:  database system is ready to accept connections